---
output: 
 md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# A multilevel spatial model to investigate voting behaviour in the 2019 UK general election

Kevin Horan<sup>1*</sup> Chris Brunsdon<sup>2</sup> and Katarina Domijan<sup>3</sup> 

<sup>1</sup> Hamilton Institute, Maynooth University, Maynooth, Ireland.\
<sup>2</sup> National Centre for Geocomputation, Maynooth University, Ireland.\
<sup>3</sup> Department of Mathematics and Statistics, Maynooth University, Maynooth, Ireland.\
<sup>*</sup> contact author: a.comber@leeds.ac.uk
<!-- badges: start -->

<!-- badges: end -->

This repository contains the code used to produce the findings discussed in this paper. The full paper is to appear in [Applied Spatial Analysis and Policy](https://link.springer.com/journal/12061).

## Abstract

*This paper presents a modelling framework which can detect the simultaneous presence of two different types of spatial process. The first is the variation from a global mean resulting from a geographical unit's 'vertical' position within a nested hierarchical structure such as the county and region where it is situated. The second is the variation at the smaller scale of individual units due to the 'horizontal' influence of nearby locations. The former is captured using a multi-level modelling structure while the latter is accounted for by an autoregressive component at the lowest level of the hierarchy. Such a model not only estimates spatially-varying parameters according to geographical scale, but also the relative contribution of each process to the overall spatial variation. As a demonstration, the study considers the association of a selection of socio-economic attributes with voting behaviour in the 2019 UK general election. It finds evidence of the presence of both types of spatial effects, and describes how they suggest different associations between census profile and voting behaviour in different parts of England and Wales.*

